### ISSUE TITLE
ONT-RefBasedAssembly Errors

### ISSUE THREAD

**Issue by radolal** [rchapman2000/ont-ref-based-assembly#1]
Hi Rayan,

We like what you are doing, we tried running the ONT-RefBasedAssembly.... This is what we get:

WARN: A process with name 'QC_Report_Trimmed' is defined more than once in module script: /home/inrblab/formation_radolal/github/pipelines/ont-ref-based-assembly/main.nf -- Make sure to not define the same function as process
WARN: A process with name 'QC_Report_Filtered' is defined more than once in module script: /home/inrblab/formation_radolal/github/pipelines/ont-ref-based-assembly/main.nf -- Make sure to not define the same function as process

**Comment by rchapman2000** [comment]
Hello @radolal! 

Those messages you posted are warnings from Nextflow, but should not affect how the pipeline runs. In the code, I wrote multiple different "paths" that the pipeline can take based on the parameters you supply. Since there are different paths, some of the steps in the pipeline are _written_ multiple times in the code (which causes those warnings from Nextflow), but they will only ever be run once during the pipeline.

Could you give me a bit more information about the issue that you are having? Could you send me the command you are running as well as the entire output from Nextflow? As well, what kind of data are you trying to run through the pipeline?

Thank you!

**Comment by radolal** [comment]
Dear Ryan,

I'm at the INRB institut now and the bioinformatic personnal here have already resolve the problem.
Thank you
Best regards

Radolal


     Le vendredi 31 mars 2023, 18:06:08 UTC+1, Ryan Chapman ***@***.***> a écrit :  
 
 


Hello @radolal!

Those messages you posted are warnings from Nextflow, but should not affect how the pipeline runs. In the code, I wrote multiple different "paths" that the pipeline can take based on the parameters you supply. Since there are different paths, some of the steps in the pipeline are written multiple times in the code (which causes those warnings from Nextflow), but they will only ever be run once during the pipeline.

Could you give me a bit more information about the issue that you are having? Could you send me the command you are running as well as the entire output from Nextflow? As well, what kind of data are you trying to run through the pipeline?

Thank you!

**Comment by rchapman2000** [comment]
I am glad to hear that!

I am going to close this issue, but please reach back out if you have any other issues!

Best,
Ryan
